# Generated by Django 2.2.3 on 2019-07-12 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revoratebot', '0002_auto_20190707_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.CharField(max_length=200)),
                ('text_uz', models.CharField(max_length=200)),
                ('text_en', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SosSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_lat', models.FloatField()),
                ('location_lon', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revoratebot.User')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='comment_templates',
            field=models.ManyToManyField(to='revoratebot.CommentTemplate'),
        ),
    ]
