# Generated by Django 2.2.3 on 2019-07-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revoratebot', '0003_auto_20190712_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='department_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
