# Generated by Django 2.2.3 on 2019-08-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revoratebot', '0005_auto_20190724_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='sossignal',
            name='department_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
